parameters:
- name: action
  displayName: Pool action
  type: string
  default: ubuntu-latest
  values:
  - Build
  - Docker
  - Deploy

trigger: none

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.action }}
  steps:
  - script: echo The image parameter is ${{ parameters.action }}```



