# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
parameters:
  - name: pipelineArg1
    displayName: pipeline Arg1?
    type: string
  - name: pipelineArg2
    displayName: pipeline Arg2?
    type: string
    
variables:
#group: my-vars
  #param : ${{ parameters.projectName }}
 #- name: param
 #param: "build"
  ${{ if eq( parameters.pipelineArg1, 'build') }}:
    param1: "build"
  ${{ if eq( parameters.pipelineArg2, 'docker') }}:
    param2: "docker"

  
steps:
- bash: echo $(param1)
- bash: echo $(param2)
- task: Bash@3
  inputs:
    targetType: 'inline'
    arguments: '$(param1) $(param2)'
    inlineScript: './Test1.sh $1 $2'


  
#- task: Bash@3
  #inputs:
    #filePath: '/Test2.sh'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
- script: echo "hello to my first Build"
#- task: ShellScript@2
  #inputs:
    #scriptPath: ./Test1.sh
    #failOnStderr: true
- task: Bash@3
  inputs:
    targetType: filePath
    #arguments: '${{ variables.param }}'
    arguments: '$(param)'
    filePath: ./Test1.sh
    failOnStderr: true
