# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Export source app'
  inputs:
    targetType: filePath
    filePath: ./export.sh
    arguments: '-r westus2 -s $(SubscriptionKey) -c $(Culture) -a $(SourceAppId)'
    workingDirectory: bash
    failOnStderr: true

- task: Bash@3
  displayName: 'Import to target app'
  inputs:
    targetType: filePath
    filePath: ./import.sh
    arguments: '-r westus2 -s $(SubscriptionKey) -c $(Culture) -a $(TargetAppId)'
    workingDirectory: bash
    failOnStderr: true

- task: Bash@3
  displayName: 'Train and Publish target app'
  inputs:
    targetType: filePath
    filePath: './train-and-publish.sh'
    arguments: '-r westus2 -s $(SubscriptionKey) -c $(Culture) -a $(TargetAppId)'
    workingDirectory: bash
    failOnStderr: true
