# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
parameters:
  - name: projectName
    displayName: project name?
    type: string
    
variables:
#group: my-vars
  #param : ${{ parameters.projectName }}
 #- name: param
 #param: "build"
 - bash: echo $(parameters.projectName)  
  #${{ if eq( parameters.projectName, 'build') }}:
   # param: "build"
 # ${{ if eq( parameters.projectName, 'Docker') }}:
    #param: "Docker"

  
steps:
- bash: echo $(param)  
- task: Bash@3
  inputs:
    targetType: 'inline'
 
  
#- task: Bash@3
  #inputs:
    #filePath: '/Test2.sh'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
- script: echo "hello to my first Build"
#- task: ShellScript@2
  #inputs:
    #scriptPath: ./Test1.sh
    #failOnStderr: true
- task: Bash@3
  inputs:
    targetType: filePath
    #arguments: '${{ variables.param }}'
    filePath: ./Test1.sh
    failOnStderr: true
